name: Build and Release Executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run electron-forge make
        run: npm run make

      - name: Archive application output
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          mkdir -p out/windows
          cp -r out/make/* out/windows

      - name: Archive application output
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          mkdir -p out/linux
          cp -r out/make/* out/linux

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          file: |
            ./out/windows/**
            ./out/linux/**
          overwrite: true